name: Matrix workflow
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test:
    name: Test Kubernetes Versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Version listings can be found here:
        # https://github.com/kubernetes-sigs/kind/releases
        node:
          #- v1.18.2
          - v1.17.5
          - v1.16.9
          - v1.15.11
          - v1.14.10
          #- v1.13.12
          #- v1.12.10
          #- v1.11.10
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: KinD (Kubernetes in Docker) Initialization
        uses: helm/kind-action@v1.0.0-rc.1
        with:
          version: v0.8.1
          node_image: kindest/node:${{ matrix.node }}
          wait: 0s
      - name: Build controller
        run: |
          make docker-build
      - name: Deploy controller
        run: |
          kind load docker-image controller:latest --name chart-testing
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | \
          bash
          [[ ! -f /usr/local/bin/kustomize ]] && sudo mv ./kustomize /usr/local/bin/kustomize
          make deploy
      - name: e2e
        run: |
          kubectl apply -f config/samples/batch_v1_cronjob.yaml
          sleep 60
          kubectl wait --for condition=complete job --all --timeout 60s
          kubectl get job -o wide
      - name: The job has failed
        if: ${{ failure() }}
        run: |
          kubectl get cronjobs.batch.tutorial.kubebuilder.io,job,pod -o wide
          kubectl get pod -o wide -n project-system
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v2
